project_id = "gymtrack"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]

[db]
port = 54322
major_version = 17

[auth]
enabled = true
site_url = "gymtrack://"
additional_redirect_urls = ["gymtrack://auth/callback"]
enable_signup = true

[auth.email]
enable_signup = true
enable_confirmations = true
